### PR TITLE
fix: Associate LSP bundle download with app preload instead of project

### PR DESCRIPTION
**Pull request by arajkumar**
Associating LSP bundle download with project causing issues when developers opens more than one project.(causes multiple LSP download and other exceptions)

Signed-off-by: Arunprasad Rajkumar <ar.arunprasad@gmail.com>

### CODE REVIEW

**Comment by arajkumar** [comment]
@jeffmaury PTAL

**Comment by jeffmaury** [comment]
Looks to me that server is downloaded each time IDE is started.
I looked at `build/idea-sandbox/plugins/org.jboss.tools.intellij.analytics` folder and found that `analytics-lsp-win.exe` got refreshed (modified date) each time I launch IDE
Also searched for the `analytics.settings.xml` in the `build` folder and could not find it

**Comment by arajkumar** [comment]
@jeffmaury , this is a problem with dev mode, can you check it by installing the plugin jar?

**Comment by jeffmaury** [comment]
Can you elaborate why it is not working in dev mode, I really don't like these debug sessions where you have to package your stuff and deploy it

**Comment by arajkumar** [comment]
@jeffmaury It is problem in `runIde` task itself, please check https://github.com/JetBrains/gradle-intellij-plugin/issues/188

**Comment by jeffmaury** [comment]
You still have an issue as your Setting class cannot be serialized/deserialized thus I can't find it after I run `runIde`
See the warning when you stop the IDE

**Comment by arajkumar** [comment]
@jeffmaury Thanks for fixing it, I missed that it need to be JavaBean :)
https://plugins.jetbrains.com/docs/intellij/persisting-state-of-components.html#implementing-the-state-class

**Comment by jeffmaury** [comment]
@arajkumar ok to merge ?

**Comment by arajkumar** [comment]
>@arajkumar ok to merge ?

@jeffmaury. yes. 

(sorry, I missed this message)

**Pull request merged**
