### PR TITLE
feat: supporting scanning go.mod

### PR DESCRIPTION
**Pull request by xieshenzh**
Support scanning dependency vulnerabilities in go.mod.

### CODE REVIEW

**Comment by xieshenzh** [comment]
@zvigrinberg @ilan-pinto please review this PR.
I disabled the CI validations for a few versions of IntelliJ, because the version of the go-plugin dependency is not compatible with these versions of IntelliJ.
After the alpha or preview release, we should not keep long term support of the plugin (i.e. supporting all the IntelliJ versions since 2021.1), because it is not common practice for IntelliJ plugins.

**Review by zvigrinberg — COMMENTED** [review]
Hi @xieshenzh 
The technical go part of the plugin looks good and off course i'll approve it, but before that, please clarify something -  does the `go-plugin` that you're relying on , is compatible with other/newer versions  ( not including IC community editions) of intelli-j since 2021.1 , excluding?

**Comment by xieshenzh** [comment]
> Hi @xieshenzh The technical and code part of the PR looks good and off course i'll approve it, but before that, please clarify something - does the `go-plugin` that you're relying on , is compatible with other/newer versions ( not including IC community editions) of intelli-j since 2021.1 , excluding?

Hi @zvigrinberg , This [plugin](https://plugins.jetbrains.com/plugin/9834-jfrog/versions/stable/309757) also has the `go-plugin` [dependency](https://github.com/jfrog/jfrog-idea-plugin/blob/b3d5cbfd7da4d6f226ccfcb3139eae7c0ff3ff01/build.gradle#L21), and it is compatible with IntelliJ 2021.3+. 

So the RHDA plugin should be compatible with IntelliJ 2021.1+. 
But when building the plugin, the `go-plugin` dependency can only be built with IntelliJ 2021.1. That's why I had to disable some github actions.

I think we should make a nightly release once this PR is merged. With that, we could verify if the compatibility works as expected.

**Review by zvigrinberg — APPROVED** [review]
lgtm,Approved
@xieshenzh As discussed, first let's release it as snapshot ( "nightly channel")

**Pull request merged**
