### PR TITLE
fix: version 2022.3 breaks by marking PreloadingActivity for internal usage

### LINKED ISSUE #35: latest plugin (0.1.1.17) is not consistent in marking vulnerability
### Problem
While editing the file, vulnerability marking disappears!

https://user-images.githubusercontent.com/3874763/108315533-8cdff580-71e1-11eb-8eb3-52fd0fcbc239.mov

### LINKED ISSUE #76: randomly keep crashing, just opening ide and closing
Following exceptions happened soon after this one, most probably they are induced.

2022-05-17T12:20:38.824
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@5c6a1b03[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@23050ab8[Wrapped task = org.wso2.lsp4intellij.editor.EditorEventManager$$Lambda$6166/0x0000000802843840@426e11b9]] rejected from java.util.concurrent.ThreadPoolExecutor@13199aac[Shutting down, pool size = 1, active threads = 1, queued tasks = 1, completed tasks = 438]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2055)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1355)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
	at java.base/java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:714)
	at org.wso2.lsp4intellij.utils.ApplicationUtils.pool(ApplicationUtils.java:52)
	at org.wso2.lsp4intellij.editor.EditorEventManager.documentSaved(EditorEventManager.java:1313)
	at org.wso2.lsp4intellij.listeners.LSPFileEventManager.lambda$fileChanged$2(LSPFileEventManager.java:88)
	at org.wso2.lsp4intellij.utils.ApplicationUtils.lambda$invokeAfterPsiEvents$0(ApplicationUtils.java:86)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:215)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

### LINKED ISSUE #81: switching from one xml to another plugin crashes
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@298bb5ee[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@52f5821c[Wrapped task = org.wso2.lsp4intellij.IntellijLanguageClient$$Lambda$3103/0x0000000102155440@66483e90]] rejected from java.util.concurrent.ThreadPoolExecutor@5a6a8218[Shutting down, pool size = 1, active threads = 1, queued tasks = 1, completed tasks = 74]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2055)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1355)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
	at java.base/java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:714)
	at org.wso2.lsp4intellij.utils.ApplicationUtils.pool(ApplicationUtils.java:52)
	at org.wso2.lsp4intellij.IntellijLanguageClient.editorOpened(IntellijLanguageClient.java:203)
	at org.wso2.lsp4intellij.listeners.LSPEditorListener.editorCreated(LSPEditorListener.java:35)
	at jdk.internal.reflect.GeneratedMethodAccessor57.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:120)
	at com.intellij.util.EventDispatcher.lambda$createMulticaster$1(EventDispatcher.java:85)
	at com.sun.proxy.$Proxy119.editorCreated(Unknown Source)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.createEditor(EditorFactoryImpl.java:209)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.createEditor(EditorFactoryImpl.java:163)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorImpl.createEditor(TextEditorImpl.java:257)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorImpl.<init>(TextEditorImpl.java:52)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl.<init>(PsiAwareTextEditorImpl.java:39)
	at com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorProvider.createEditor(PsiAwareTextEditorProvider.java:31)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.createComposite(FileEditorManagerImpl.java:1087)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4Edt(FileEditorManagerImpl.java:988)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl4$17(FileEditorManagerImpl.java:961)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.runBulkTabChange(FileEditorManagerImpl.java:1697)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl4$18(FileEditorManagerImpl.java:960)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:490)
	at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:523)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl4(FileEditorManagerImpl.java:957)
	at com.jetbrains.rdserver.fileEditors.BackendServerFileEditorManager.openFileImpl4(BackendServerFileEditorManager.kt:34)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openFileImpl2$14(FileEditorManagerImpl.java:885)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:210)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:174)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:164)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:150)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileImpl2(FileEditorManagerImpl.java:884)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileWithProviders(FileEditorManagerImpl.java:764)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$openEditorImpl$22(FileEditorManagerImpl.java:1228)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:210)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:174)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:164)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:150)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openEditorImpl(FileEditorManagerImpl.java:1222)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.openFileEditor(FileEditorManagerImpl.java:1198)
	at com.intellij.openapi.fileEditor.FileEditorManager.openEditor(FileEditorManager.java:233)
	at com.intellij.openapi.fileEditor.FileNavigatorImpl.navigateInAnyFileEditor(FileNavigatorImpl.java:97)
	at com.intellij.openapi.fileEditor.FileNavigatorImpl.navigateInEditor(FileNavigatorImpl.java:78)
	at com.intellij.openapi.fileEditor.FileNavigatorImpl.navigateInEditorOrNativeApp(FileNavigatorImpl.java:63)
	at com.intellij.openapi.fileEditor.FileNavigatorImpl.navigate(FileNavigatorImpl.java:46)
	at com.intellij.openapi.fileEditor.OpenFileDescriptor.navigate(OpenFileDescriptor.java:89)
	at com.intellij.psi.impl.source.PsiFileImpl.navigate(PsiFileImpl.java:915)
	at com.intellij.codeInsight.navigation.NavigationUtil.lambda$openFileWithPsiElement$2(NavigationUtil.java:174)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:219)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:174)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:164)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:150)
	at com.intellij.codeInsight.navigation.NavigationUtil.openFileWithPsiElement(NavigationUtil.java:170)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.navigate(AbstractPsiBasedNode.java:268)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.navigate(AbstractPsiBasedNode.java:278)
	at com.intellij.ide.projectView.impl.nodes.PsiFileNode.navigate(PsiFileNode.java:116)
	at com.intellij.util.OpenSourceUtil.navigateToSource(OpenSourceUtil.java:126)
	at com.intellij.util.OpenSourceUtil.navigate(OpenSourceUtil.java:81)
	at com.intellij.util.OpenSourceUtil.navigate(OpenSourceUtil.java:59)
	at com.intellij.util.OpenSourceUtil.navigate(OpenSourceUtil.java:52)
	at com.intellij.util.OpenSourceUtil.openSourcesFrom(OpenSourceUtil.java:20)
	at com.intellij.util.EditSourceOnDoubleClickHandler$TreeMouseListener.processDoubleClick(EditSourceOnDoubleClickHandler.java:172)
	at com.intellij.util.EditSourceOnDoubleClickHandler$TreeMouseListener.onDoubleClick(EditSourceOnDoubleClickHandler.java:166)
	at com.intellij.ui.DoubleClickListener.onClick(DoubleClickListener.java:30)
	at com.intellij.ui.ClickListener$1.mouseReleased(ClickListener.java:59)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6654)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at com.intellij.ui.treeStructure.Tree.processMouseEvent(Tree.java:394)
	at com.intellij.ide.dnd.aware.DnDAwareTree.processMouseEvent(DnDAwareTree.java:44)
	at java.desktop/java.awt.Component.processEvent(Component.java:6419)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5029)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2793)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:820)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:743)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:119)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

### LINKED ISSUE #91: The plugin breaks with major 2022.3
Looks like between _IntelliJ_ [2022.2](https://github.com/JetBrains/intellij-community/blob/222/platform/ide-core/src/com/intellij/openapi/application/PreloadingActivity.java) and [2022.3](https://github.com/JetBrains/intellij-community/blob/223/platform/ide-core/src/com/intellij/openapi/application/PreloadingActivity.kt), this extension was marked _Internal_.
As mentioned in its Javadoc, 3rd party plugins should use the Startup Activity extension instead.

The _Preload Activity Extension_ is used to download the executables for both the _CRDA CLI_ and the _LSP Server_.

Based on my investigation, neither the [PreloadLanguageServer](https://github.com/redhat-developer/intellij-dependency-analytics/blob/main/src/main/java/org/jboss/tools/intellij/analytics/PreloadLanguageServer.java) nor the [PreloadCli](https://github.com/redhat-developer/intellij-dependency-analytics/blob/main/src/main/java/org/jboss/tools/intellij/stackanalysis/PreloadCli.java) _PreloadingActivity_ implementations are being invoked, so the executables aren't being downloaded.

From a user experience perspective, the _LSP Servers_ aren't running, so no error reporting while inline editing.
As well as initiating a Stack Analysis report, throws an OS error stating the executable is not found.

### LINKED ISSUE #92: LSP Server throws exceptions
It appears as if the LSP server doesn't shutdown completely when editing is done, which causes an error to be thrown when trying to spin up another instance:

_Idea version_ **2022.2.4**
_Dependency Analytics plugin version_ **0.5.0.53**
_Operating System_ **Fedora 36**

Instructions:
- Open a supported package file
- Wait for the green light indicating the lsp server is up
- Close the package file
- Note the yellow light indicating the lsp server is not fully down
- Open another supported package file
- Note the exception thrown
- Note the red light indicating the lsp server is down
Now you should be able to open files.

intellij-lsp-fail

### PR DESCRIPTION
**Pull request by TomerFi**
Fixes #35, Fixes #76, Fixes #81, Fixes #91, Fixes #92

**Tested locally with versions**:

- 2021.1 (our minimum target)
- 2022.2
- 2022.3 (the latest version)

**Edit 1**:
Looks like this fix, though fixed the issue at hand, introduced a new one.
With this fix, diagnostic is only performed for modifying an already open file, and not for opening one.

**Edit 2**:
The cause for the error described in _Edit 1_ is _lsp4intellij_.
This bug was introduced in version [0.95.1](https://github.com/ballerina-platform/lsp4intellij/releases/tag/0.95.1), and can be demonstrated using the _master-snapshot_ as well.
However, pinning the version to [0.95.0](https://github.com/ballerina-platform/lsp4intellij/releases/tag/0.95.0) resolves this issue.
Pinning the version is handled in #106.

### CODE REVIEW

**Comment by TomerFi** [comment]
@jeffmaury I have another version of this fix stashed on my computer.
Which I think is better.

The version I have stashed uses an _application lifecycle listener_ to start the downloading the executables as _different threads_ when the application gets created.
Meaning we start the download even **before the welcome screen**.

Th version I ended up pushing starts the download processes as _post startup background activities_.
Meaning we start the download only **after the user opens a project**.

I think the _application lifecycle listener_ technique is better,
But it introduces more and bigger modifications to the code base.
So I went with the _post startup background activities_.

If you prefer the first one,
I can re-push.

**Review by jeffmaury — CHANGES_REQUESTED** [review]
Dependency changes should be in a separate PR

**Comment by TomerFi** [comment]
> Dependency changes should be in a separate PR

@jeffmaury 
https://github.com/redhat-developer/intellij-dependency-analytics/pull/106

**Comment by TomerFi** [comment]
rebased from the master after previous prs merged.

**Review by jeffmaury — CHANGES_REQUESTED** [review]
Seems to be several concerns are mixed in this PR

**Comment by TomerFi** [comment]
> Seems to be several concerns are mixed in this PR

@jeffmaury 
First of all, thank you for your review.
Secondly, if there are multiple concerns here, it's because they are entangled with each other.

**Background**
This project uses `lsp4intellij@master-SNAPSHOT` (see #106).
This projects latest release ([0.5.0](https://github.com/redhat-developer/intellij-dependency-analytics/releases/tag/0.5.0)) was on January 16th.
The README for _lsp4intellij_ on that date looked something like [this](https://github.com/ballerina-platform/lsp4intellij/tree/8bba98cce03db32fdfb794c2f51984663b715e80), which matches this plugin configuration at the time of the release build.

Today, the configuration is different, not only is it now used as a `application service` instead of the deprecated `application component`, but the extensions configuration is completely different now. You can check [this compare link](https://github.com/ballerina-platform/lsp4intellij/compare/8bba98cce03db32fdfb794c2f51984663b715e80..master) and pay extra attention to the original _README.md_ vs. the current _plugin.xml.example_.

**Initial Issue**
As explained in #91, IntelliJ 2022.3 broke the the way we download the executables.
To fix that, I switched the usage of the broken _Preload Activity_ to a more stable approach using the _Application Lifecycle Listener_.

This seems to do the trick, now the executables were downloaded as expected, and I could verify _stack analysis_ was working again.

But... I couldn't verify _component analysis_ because, as mentioned in the background, we're using a _SNAPSHOT_ _lsp4intellij_ and its configuration was changed dramatically from the last build done for this plugin's _0.5.0_ release.
So I adapted the configuration accordingly and pushed this PR.

**Happy Side Effect**
As I was verifying our fix works with the adapted configuration of _lsp4intellij_, I was also able to verify that this configuration adaptation seems to also resolves #35, #76, #81, and #92.

**Comment by jeffmaury** [comment]
I see another PR for updating the lsp4intellij dependency, so:

- are the changes related to lsp4intellij in this PR relevant in the other PR and in that case they should be in this PR
- if not they should be removed and this PR rebased after the other PR has been merged

**Comment by TomerFi** [comment]
> I see another PR for updating the lsp4intellij dependency, so:
> 
> * are the changes related to lsp4intellij in this PR relevant in the other PR and in that case they should be in this PR
> * if not they should be removed and this PR rebased after the other PR has been merged

@jeffmaury haa you happen to see another PR, lucky me.
Well... they are not related, but I think you already know that.
The "other PR" you referring to is #106  and is not related and it is meant to fix another issue caused by the poor design of this plugin, i.e. using unstable snapshot versions.

You know what...
Either merge, or put it on hold.

I'm done jumping through hoops for you.
You've been trying to make my work harder since last week and I'm tired of it.

I'm gonna refer this to our managers and let them decide.

Good day!

**Comment by TomerFi** [comment]
@jeffmaury
> I see another PR for updating the lsp4intellij dependency, so:

Yeah, you mean #106 which I opened based on one of your requests.

> * are the changes related to lsp4intellij in this PR relevant in the other PR and in that case they should be in this PR

They were in this PR but you asked me to take it out:
image

> * if not they should be removed and this PR rebased after the other PR has been merged

They are not related, #106  is meant to fix another issue caused by a bad practice used in this plugin's design.

i.e. using unstable snapshot versions made us oblivious to the fact that _lsp4intellij_ version _0.95.1_ broke diagnostics for opening files (works only for modifying files), hence #106 is pinning _lsp4intellij_ to the last known working version _0.95.0_ instead of the unstable snapshot version used today.

I'm sorry, I'm not going to change this or the other remaining PR again, if you don't want to merge it - don't.
If you're not merging this, please put it hold and do not close it.

Have a good day.

**Comment by TomerFi** [comment]
Rebased.

**Comment by ruromero** [comment]
@jeffmaury do you have any further comments? If not we will merge it.
Thanks in advance.

**Pull request merged**
